import type { templateData, planLockState, checkProgress } from './types';

const enrich = (train: templateData): templateData => train;

export const mockOldPlan: templateData[] = [
  enrich({
    id: '1',
    trainNo: 'G473',
    trainType: 'high-speed',
    originStation: '北京南',
    terminalStation: '上海虹桥',
    arrivalTime: '09:05',
    departureTime: '09:25',
    track: '4',
    platform: '4',
    gates: '4A、5A',
    exitGate: '2号口',
    formation: 'CR400AF',
    model: '16编',
    stopDirection: '北18',
    orderDirection: '正序',
    landmarkColor: '绿',
    focusFlag: true,
    waterSupply: '有',
    sewageSuction: '有',
    baggage: '有',
    status: '始发',
  }),
  enrich({
    id: '2',
    trainNo: 'G1234',
    trainType: 'high-speed',
    originStation: '北京南',
    terminalStation: '上海虹桥',
    arrivalTime: '10:00',
    departureTime: '10:15',
    track: '5',
    platform: '5',
    gates: '5A、5B',
    exitGate: '2号口',
    formation: 'CR400BF',
    model: '16编',
    stopDirection: '北18',
    orderDirection: '正序',
    landmarkColor: '绿',
    focusFlag: false,
    waterSupply: '有',
    sewageSuction: '有',
    baggage: '有',
    status: '始发',
  }),
  enrich({
    id: '3',
    trainNo: 'D3710',
    trainType: 'high-speed',
    originStation: '合肥南',
    terminalStation: '上海虹桥',
    arrivalTime: '14:30',
    departureTime: '14:45',
    track: '2',
    platform: '2',
    gates: '2A',
    exitGate: '1号口',
    formation: 'CRH380A',
    model: '8编',
    stopDirection: '北12',
    orderDirection: '倒序',
    landmarkColor: '黄',
    focusFlag: true,
    waterSupply: '无',
    sewageSuction: '有',
    baggage: '无',
    status: '途径',
  }),
  enrich({
    id: '4',
    trainNo: 'G7181',
    trainType: 'high-speed',
    originStation: '南京南',
    terminalStation: '杭州东',
    arrivalTime: '15:00',
    departureTime: '15:15',
    track: '4',
    platform: '4',
    gates: '4A、5A',
    exitGate: '3号口',
    formation: 'CR400AF',
    model: '16编',
    stopDirection: '北10',
    orderDirection: '正序',
    landmarkColor: '红',
    focusFlag: false,
    waterSupply: '有',
    sewageSuction: '无',
    baggage: '有',
    status: '始发',
  }),
  enrich({
    id: '5',
    trainNo: 'G4321',
    trainType: 'high-speed',
    originStation: '杭州东',
    terminalStation: '上海虹桥',
    arrivalTime: '10:00',
    departureTime: '10:15',
    track: '3',
    platform: '3',
    gates: '3A',
    exitGate: '2号口',
    formation: 'CR400BF',
    model: '16编',
    stopDirection: '北16',
    orderDirection: '正序',
    landmarkColor: '绿',
    focusFlag: false,
    waterSupply: '有',
    sewageSuction: '有',
    baggage: '有',
    status: '始发',
  }),
  enrich({
    id: '6',
    trainNo: 'G5678',
    trainType: 'high-speed',
    originStation: '杭州东',
    terminalStation: '北京南',
    arrivalTime: '11:00',
    departureTime: '11:10',
    track: '6',
    platform: '6',
    gates: '6A',
    exitGate: '4号口',
    formation: 'CRH380B',
    model: '16编',
    stopDirection: '北14',
    orderDirection: '倒序',
    landmarkColor: '蓝',
    focusFlag: false,
    waterSupply: '有',
    sewageSuction: '有',
    baggage: '无',
    status: '途径',
  }),
  enrich({
    id: '7',
    trainNo: 'D8901',
    trainType: 'high-speed',
    originStation: '上海虹桥',
    terminalStation: '南京南',
    arrivalTime: '13:00',
    departureTime: '13:15',
    track: '7',
    platform: '7',
    gates: '7A',
    exitGate: '5号口',
    formation: 'CRH380A',
    model: '8编',
    stopDirection: '北18',
    orderDirection: '倒序',
    landmarkColor: '绿',
    focusFlag: true,
    waterSupply: '无',
    sewageSuction: '无',
    baggage: '有',
    status: '途径',
  }),
  enrich({
    id: '8',
    trainNo: 'G1023',
    trainType: 'high-speed',
    originStation: '上海虹桥',
    terminalStation: '苏州北',
    arrivalTime: '08:30',
    departureTime: '08:45',
    track: '8',
    platform: '8',
    gates: '8A',
    exitGate: '1号口',
    formation: 'CR400AF',
    model: '16编',
    stopDirection: '北11',
    orderDirection: '倒序',
    landmarkColor: '黄',
    focusFlag: false,
    waterSupply: '有',
    sewageSuction: '有',
    baggage: '无',
    status: '途径',
  }),
  enrich({
    id: '9',
    trainNo: 'D2345',
    trainType: 'high-speed',
    originStation: '杭州东',
    terminalStation: '上海虹桥',
    arrivalTime: '16:00',
    departureTime: '16:10',
    track: '9',
    platform: '9',
    gates: '9A',
    exitGate: '3号口',
    formation: 'CRH2A',
    model: '8编',
    stopDirection: '北12',
    orderDirection: '正序',
    landmarkColor: '红',
    focusFlag: false,
    waterSupply: '无',
    sewageSuction: '有',
    baggage: '无',
    status: '终到',
  }),
  enrich({
    id: '10',
    trainNo: 'G9988',
    trainType: 'high-speed',
    originStation: '上海虹桥',
    terminalStation: '广州南',
    arrivalTime: '17:30',
    departureTime: '17:45',
    track: '10',
    platform: '10',
    gates: '10A',
    exitGate: '2号口',
    formation: 'CR400BF',
    model: '16编',
    stopDirection: '北15',
    orderDirection: '倒序',
    landmarkColor: '蓝',
    focusFlag: false,
    waterSupply: '有',
    sewageSuction: '有',
    baggage: '有',
    status: '途径',
  }),
];

export const mockNewPlan: templateData[] = [
  enrich({
    id: '1',
    trainNo: 'G473',
    trainType: 'high-speed',
    originStation: '北京南',
    terminalStation: '上海虹桥',
    arrivalTime: '09:05',
    departureTime: '09:25',
    track: '4',
    platform: '4',
    gates: '4A、5A',
    exitGate: '2号口',
    formation: 'CR400AF',
    model: '16编',
    stopDirection: '北18',
    orderDirection: '正序',
    landmarkColor: '绿',
    focusFlag: true,
    waterSupply: '有',
    sewageSuction: '有',
    baggage: '有',
    status: '始发',
  }),
  enrich({
    id: '2',
    trainNo: 'G1234',
    trainType: 'high-speed',
    originStation: '北京南',
    terminalStation: '上海虹桥',
    arrivalTime: '09:10',
    departureTime: '09:25',
    track: '5',
    platform: '5',
    gates: '5A、5B',
    exitGate: '2号口',
    formation: 'CR400BF',
    model: '16编',
    stopDirection: '北18',
    orderDirection: '正序',
    landmarkColor: '绿',
    focusFlag: false,
    waterSupply: '有',
    sewageSuction: '有',
    baggage: '有',
    status: '始发',
  }),
  enrich({
    id: '3',
    trainNo: 'D3710',
    trainType: 'high-speed',
    originStation: '合肥南',
    terminalStation: '上海虹桥',
    arrivalTime: '14:30',
    departureTime: '14:45',
    track: '2',
    platform: '2',
    gates: '2B',
    exitGate: '1号口',
    formation: 'CRH380A',
    model: '8编',
    stopDirection: '北12',
    orderDirection: '倒序',
    landmarkColor: '黄',
    focusFlag: true,
    waterSupply: '无',
    sewageSuction: '有',
    baggage: '无',
    status: '途径',
  }),
  enrich({
    id: '4',
    trainNo: 'G7181',
    trainType: 'high-speed',
    originStation: '南京南',
    terminalStation: '杭州东',
    arrivalTime: '15:00',
    departureTime: '15:15',
    track: '5',
    platform: '4',
    gates: '4A、5A',
    exitGate: '3号口',
    formation: 'CR400AF',
    model: '16编',
    stopDirection: '北10',
    orderDirection: '正序',
    landmarkColor: '红',
    focusFlag: false,
    waterSupply: '有',
    sewageSuction: '无',
    baggage: '有',
    status: '始发',
  }),
  enrich({
    id: '6',
    trainNo: 'G5678',
    trainType: 'high-speed',
    originStation: '杭州东',
    terminalStation: '北京南',
    arrivalTime: '11:00',
    departureTime: '11:10',
    track: '6',
    platform: '6',
    gates: '6A',
    exitGate: '4号口',
    formation: 'CRH380B',
    model: '16编',
    stopDirection: '北14',
    orderDirection: '倒序',
    landmarkColor: '蓝',
    focusFlag: false,
    waterSupply: '有',
    sewageSuction: '有',
    baggage: '无',
    status: '途径',
  }),
  enrich({
    id: '7',
    trainNo: 'D8901',
    trainType: 'high-speed',
    originStation: '上海虹桥',
    terminalStation: '南京南',
    arrivalTime: '13:00',
    departureTime: '13:15',
    track: '7',
    platform: '7',
    gates: '7A',
    exitGate: '5号口',
    formation: 'CRH380A',
    model: '8编',
    stopDirection: '北18',
    orderDirection: '倒序',
    landmarkColor: '绿',
    focusFlag: true,
    waterSupply: '无',
    sewageSuction: '无',
    baggage: '有',
    status: '途径',
  }),
  enrich({
    id: '8',
    trainNo: 'G1023',
    trainType: 'high-speed',
    originStation: '上海虹桥',
    terminalStation: '苏州北',
    arrivalTime: '08:30',
    departureTime: '08:45',
    track: '8',
    platform: '8',
    gates: '8A',
    exitGate: '1号口',
    formation: 'CR400AF',
    model: '16编',
    stopDirection: '北11',
    orderDirection: '倒序',
    landmarkColor: '黄',
    focusFlag: false,
    waterSupply: '有',
    sewageSuction: '有',
    baggage: '无',
    status: '途径',
  }),
  enrich({
    id: '9',
    trainNo: 'D2345',
    trainType: 'high-speed',
    originStation: '杭州东',
    terminalStation: '上海虹桥',
    arrivalTime: '16:00',
    departureTime: '16:10',
    track: '9',
    platform: '9',
    gates: '9A',
    exitGate: '3号口',
    formation: 'CRH2A',
    model: '8编',
    stopDirection: '北12',
    orderDirection: '正序',
    landmarkColor: '红',
    focusFlag: false,
    waterSupply: '无',
    sewageSuction: '有',
    baggage: '无',
    status: '终到',
  }),
  enrich({
    id: '10',
    trainNo: 'G9988',
    trainType: 'high-speed',
    originStation: '上海虹桥',
    terminalStation: '广州南',
    arrivalTime: '17:30',
    departureTime: '17:45',
    track: '10',
    platform: '10',
    gates: '10A',
    exitGate: '2号口',
    formation: 'CR400BF',
    model: '16编',
    stopDirection: '北15',
    orderDirection: '倒序',
    landmarkColor: '蓝',
    focusFlag: false,
    waterSupply: '有',
    sewageSuction: '有',
    baggage: '有',
    status: '途径',
  }),
  enrich({
    id: '11',
    trainNo: 'D5678',
    trainType: 'high-speed',
    originStation: '南京南',
    terminalStation: '杭州东',
    arrivalTime: '14:30',
    departureTime: '14:45',
    track: '3',
    platform: '3',
    gates: '3A、3B',
    exitGate: '4号口',
    formation: 'CRH380A',
    model: '8编',
    stopDirection: '北13',
    orderDirection: '正序',
    landmarkColor: '绿',
    focusFlag: true,
    waterSupply: '有',
    sewageSuction: '有',
    baggage: '无',
    status: '始发',
  }),
  enrich({
    id: '12',
    trainNo: 'Z9999',
    trainType: 'normal',
    originStation: '上海',
    terminalStation: '北京',
    arrivalTime: '22:00',
    departureTime: '22:15',
    track: '11',
    platform: '11',
    gates: '11A',
    exitGate: '5号口',
    formation: '25T',
    model: '18编',
    stopDirection: '北15',
    orderDirection: '正序',
    landmarkColor: '红',
    focusFlag: true,
    waterSupply: '有',
    sewageSuction: '有',
    baggage: '有',
    status: '途径',
  }),
];

export const mockLockStates: planLockState[] = [
  {
    id: 'lock-1',
    trainNo: 'G473',
    diagramNo: '2025-Q4',
    isLocked: true,
    lockedAt: '2026-05-08 14:30',
    lockedBy: '张三',
    lockedReason: '始发车需确认',
  },
  {
    id: 'lock-2',
    trainNo: 'G7181',
    diagramNo: '2025-Q4',
    isLocked: true,
    lockedAt: '2026-05-08 14:45',
    lockedBy: '李四',
    lockedReason: '等待调度确认',
    regeneratedAt: '2026-05-08 14:50',
    regeneratedData: mockNewPlan.find(t => t.trainNo === 'G7181'),
    conflictStatus: 'detected',
  },
];

export const mockCheckProgress: checkProgress[] = [
  { id: 'check-1', trainNo: 'G473', diagramNo: '2025-Q4', checkStatus: 'checked', checkedBy: '张三', checkedAt: '2026-05-08 14:35' },
  { id: 'check-2', trainNo: 'G1234', diagramNo: '2025-Q4', checkStatus: 'checked', checkedBy: '张三', checkedAt: '2026-05-08 14:36' },
  { id: 'check-3', trainNo: 'D3710', diagramNo: '2025-Q4', checkStatus: 'questioned', checkedBy: '李四', checkedAt: '2026-05-08 14:40', notes: '检票口变更需确认', questionType: 'mismatch_paper' },
  { id: 'check-4', trainNo: 'G7181', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
  { id: 'check-5', trainNo: 'G4321', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
  { id: 'check-6', trainNo: 'G5678', diagramNo: '2025-Q4', checkStatus: 'checked', checkedBy: '张三', checkedAt: '2026-05-08 14:38' },
  { id: 'check-7', trainNo: 'D8901', diagramNo: '2025-Q4', checkStatus: 'confirmed', checkedBy: '王五', checkedAt: '2026-05-08 14:42' },
  { id: 'check-8', trainNo: 'G1023', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
  { id: 'check-9', trainNo: 'D2345', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
  { id: 'check-10', trainNo: 'G9988', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
  { id: 'check-11', trainNo: 'D5678', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
  { id: 'check-12', trainNo: 'Z9999', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
];

export const planGenerateTime = '2026-05-08 14:30';
export const lastCheckTime = '2026-05-08 14:42';
