import type { templateData, planLockState, checkProgress } from './types';

export const mockOldPlan: templateData[] = [
  {
    id: '1',
    trainNo: 'G473',
    trainType: 'high-speed',
    arrivalTime: '09:05',
    departureTime: '09:25',
    track: '4',
    platform: '4',
    gates: '4A、5A',
    formation: 'CR400AF',
    model: '16编',
    status: '始发',
  },
  {
    id: '2',
    trainNo: 'G1234',
    trainType: 'high-speed',
    arrivalTime: '10:00',
    departureTime: '10:15',
    track: '5',
    platform: '5',
    gates: '5A、5B',
    formation: 'CR400BF',
    model: '16编',
    status: '始发',
  },
  {
    id: '3',
    trainNo: 'D3710',
    trainType: 'high-speed',
    arrivalTime: '14:30',
    departureTime: '14:45',
    track: '2',
    platform: '2',
    gates: '2A',
    formation: 'CRH380A',
    model: '8编',
    status: '途径',
  },
  {
    id: '4',
    trainNo: 'G7181',
    trainType: 'high-speed',
    arrivalTime: '15:00',
    departureTime: '15:15',
    track: '4',
    platform: '4',
    gates: '4A、5A',
    formation: 'CR400AF',
    model: '16编',
    status: '始发',
  },
  {
    id: '5',
    trainNo: 'G4321',
    trainType: 'high-speed',
    arrivalTime: '10:00',
    departureTime: '10:15',
    track: '3',
    platform: '3',
    gates: '3A',
    formation: 'CR400BF',
    model: '16编',
    status: '始发',
  },
  {
    id: '6',
    trainNo: 'G5678',
    trainType: 'high-speed',
    arrivalTime: '11:00',
    departureTime: '11:10',
    track: '6',
    platform: '6',
    gates: '6A',
    formation: 'CRH380B',
    model: '16编',
    status: '途径',
  },
  {
    id: '7',
    trainNo: 'D8901',
    trainType: 'high-speed',
    arrivalTime: '13:00',
    departureTime: '13:15',
    track: '7',
    platform: '7',
    gates: '7A',
    formation: 'CRH380A',
    model: '8编',
    status: '途径',
  },
  {
    id: '8',
    trainNo: 'G1023',
    trainType: 'high-speed',
    arrivalTime: '08:30',
    departureTime: '08:45',
    track: '8',
    platform: '8',
    gates: '8A',
    formation: 'CR400AF',
    model: '16编',
    status: '途径',
  },
  {
    id: '9',
    trainNo: 'D2345',
    trainType: 'high-speed',
    arrivalTime: '16:00',
    departureTime: '16:10',
    track: '9',
    platform: '9',
    gates: '9A',
    formation: 'CRH2A',
    model: '8编',
    status: '终到',
  },
  {
    id: '10',
    trainNo: 'G9988',
    trainType: 'high-speed',
    arrivalTime: '17:30',
    departureTime: '17:45',
    track: '10',
    platform: '10',
    gates: '10A',
    formation: 'CR400BF',
    model: '16编',
    status: '途径',
  },
];

export const mockNewPlan: templateData[] = [
  {
    id: '1',
    trainNo: 'G473',
    trainType: 'high-speed',
    arrivalTime: '09:05',
    departureTime: '09:25',
    track: '4',
    platform: '4',
    gates: '4A、5A',
    formation: 'CR400AF',
    model: '16编',
    status: '始发',
  },
  {
    id: '2',
    trainNo: 'G1234',
    trainType: 'high-speed',
    arrivalTime: '09:10',
    departureTime: '09:25',
    track: '5',
    platform: '5',
    gates: '5A、5B',
    formation: 'CR400BF',
    model: '16编',
    status: '始发',
  },
  {
    id: '3',
    trainNo: 'D3710',
    trainType: 'high-speed',
    arrivalTime: '14:30',
    departureTime: '14:45',
    track: '2',
    platform: '2',
    gates: '2B',
    formation: 'CRH380A',
    model: '8编',
    status: '途径',
  },
  {
    id: '4',
    trainNo: 'G7181',
    trainType: 'high-speed',
    arrivalTime: '15:00',
    departureTime: '15:15',
    track: '5',
    platform: '4',
    gates: '4A、5A',
    formation: 'CR400AF',
    model: '16编',
    status: '始发',
  },
  {
    id: '6',
    trainNo: 'G5678',
    trainType: 'high-speed',
    arrivalTime: '11:00',
    departureTime: '11:10',
    track: '6',
    platform: '6',
    gates: '6A',
    formation: 'CRH380B',
    model: '16编',
    status: '途径',
  },
  {
    id: '7',
    trainNo: 'D8901',
    trainType: 'high-speed',
    arrivalTime: '13:00',
    departureTime: '13:15',
    track: '7',
    platform: '7',
    gates: '7A',
    formation: 'CRH380A',
    model: '8编',
    status: '途径',
  },
  {
    id: '8',
    trainNo: 'G1023',
    trainType: 'high-speed',
    arrivalTime: '08:30',
    departureTime: '08:45',
    track: '8',
    platform: '8',
    gates: '8A',
    formation: 'CR400AF',
    model: '16编',
    status: '途径',
  },
  {
    id: '9',
    trainNo: 'D2345',
    trainType: 'high-speed',
    arrivalTime: '16:00',
    departureTime: '16:10',
    track: '9',
    platform: '9',
    gates: '9A',
    formation: 'CRH2A',
    model: '8编',
    status: '终到',
  },
  {
    id: '10',
    trainNo: 'G9988',
    trainType: 'high-speed',
    arrivalTime: '17:30',
    departureTime: '17:45',
    track: '10',
    platform: '10',
    gates: '10A',
    formation: 'CR400BF',
    model: '16编',
    status: '途径',
  },
  {
    id: '11',
    trainNo: 'D5678',
    trainType: 'high-speed',
    arrivalTime: '14:30',
    departureTime: '14:45',
    track: '3',
    platform: '3',
    gates: '3A、3B',
    formation: 'CRH380A',
    model: '8编',
    status: '始发',
  },
  {
    id: '12',
    trainNo: 'Z9999',
    trainType: 'normal',
    arrivalTime: '22:00',
    departureTime: '22:15',
    track: '11',
    platform: '11',
    gates: '11A',
    formation: '25T',
    model: '18编',
    status: '途径',
  },
];

export const mockLockStates: planLockState[] = [
  {
    id: 'lock-1',
    trainNo: 'G473',
    diagramNo: '2025-Q4',
    isLocked: true,
    lockedAt: '2026-05-08 14:30',
    lockedBy: '张三',
    lockedReason: '始发车需确认',
  },
  {
    id: 'lock-2',
    trainNo: 'G7181',
    diagramNo: '2025-Q4',
    isLocked: true,
    lockedAt: '2026-05-08 14:45',
    lockedBy: '李四',
    lockedReason: '等待调度确认',
    regeneratedAt: '2026-05-08 14:50',
    regeneratedData: mockNewPlan.find(t => t.trainNo === 'G7181'),
    conflictStatus: 'detected',
  },
];

export const mockCheckProgress: checkProgress[] = [
  { id: 'check-1', trainNo: 'G473', diagramNo: '2025-Q4', checkStatus: 'checked', checkedBy: '张三', checkedAt: '2026-05-08 14:35' },
  { id: 'check-2', trainNo: 'G1234', diagramNo: '2025-Q4', checkStatus: 'checked', checkedBy: '张三', checkedAt: '2026-05-08 14:36' },
  { id: 'check-3', trainNo: 'D3710', diagramNo: '2025-Q4', checkStatus: 'questioned', checkedBy: '李四', checkedAt: '2026-05-08 14:40', notes: '检票口变更需确认', questionType: 'mismatch_paper' },
  { id: 'check-4', trainNo: 'G7181', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
  { id: 'check-5', trainNo: 'G4321', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
  { id: 'check-6', trainNo: 'G5678', diagramNo: '2025-Q4', checkStatus: 'checked', checkedBy: '张三', checkedAt: '2026-05-08 14:38' },
  { id: 'check-7', trainNo: 'D8901', diagramNo: '2025-Q4', checkStatus: 'confirmed', checkedBy: '王五', checkedAt: '2026-05-08 14:42' },
  { id: 'check-8', trainNo: 'G1023', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
  { id: 'check-9', trainNo: 'D2345', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
  { id: 'check-10', trainNo: 'G9988', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
  { id: 'check-11', trainNo: 'D5678', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
  { id: 'check-12', trainNo: 'Z9999', diagramNo: '2025-Q4', checkStatus: 'unchecked' },
];

export const planGenerateTime = '2026-05-08 14:30';
export const lastCheckTime = '2026-05-08 14:42';
export const lastCheckUser = '王五';
